// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByResetToken(ctx context.Context, resetToken pgtype.Text) (GetUserByResetTokenRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error)
	UpdateResetToken(ctx context.Context, arg UpdateResetTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	VerifyUser(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
